config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  get '/signup', to: 'users#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :draft, -> { where(draft_status: true)}
  scope :published, -> { where(draft_status: false)}
  scope :search, -> (search_query) { where('body LIKE :query_string OR subject LIKE :query_string', query_string: "%#{search_query}%") }
  validates :body, presence: true

  # def self.search(foo)
  #   where('body LIKE ? OR subject LIKE ?', "%#{foo}%", "%#{foo}%")
  # end

  # def self.published
  #   where(draft_status: false)
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Add save handlers for formatting data
  before_create :create_remember_token
  before_save :normalize_fields

  # Validates name:
  validates :name,
    presence: true,
    length: { maximum: 50}

  # Validates email:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false},
    format: { with: /[^@]+@[^@]/ }

  # Validates password:
  validates :password,
    length: { minimum: 8}

  # Secure password features
  has_secure_password

  # create new rember token for the user
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end
  def self.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

private
  
  # Create a new session token for the user
  def create_remember_token
    remember_token = User.hash(User.new_remember_token)
  end

  def normalize_fields
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.unscoped
    @posts.search(params[:q]) if params[:q]
    params[:drafts] ? @posts.draft : @posts.published
  end

  # def drafts
  #   @posts = Post.draft
  #   render "index"
  # end

  # def search
  #   @posts = Post.search(params[:q])
  #   render "index"
  # end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:subject, :body, :published_at, :draft_status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  def edit
  end
  def update
  end
  def destroy
  end
 private
  def users_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :draft_status %><br>
    <%= f.check_box :draft_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_search_form.html.erb
<%= form_tag(posts_path, method: "get") do %>
<!--   <%= label_tag(:q, "Search for:") %> -->
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<p>
  <br/> <!-- don't style like this, this sucks -->
  <%= render "search_form" %>
</p>
<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>Published at</th>
      <!-- <th>Draft status</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.subject %></td>
        <td><%= post.body %></td>
        <td><%= post.published_at %></td>
<!--         <td><%= link_to 'Show', post %></td> -->
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @post.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @post.published_at %>
</p>

<p>
  <strong>Draft status:</strong>
  <%= @post.draft_status %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<p>
  <br/> <!-- don't style like this, this sucks -->
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin?</th>
      <!-- <th>Draft status</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.admin.to_s %></td>
<!--         <td><%= link_to 'Show', user %></td> -->
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <b>Errors:</b>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end -%>

<%= form_for @user do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.label :email %>
   <%= f.text_field :email %>

   <%= f.label :password %>
   <%= f.password_field :password %>

   <%= f.label :password_confirmation, 'Confirm Password' %>
   <%= f.password_field :password_confirmation %>

   <%= f.submit 'Submit', id: 'submit' %>
 <% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.email %></p>
<p><%= @user.admin %></p>